import { useState } from 'react'
import { useKV } from '@github/spark/hooks'
import { 
  CheckCircle, 
  XCircle,
  Clock,
  GitMerge,
  GitBranch,
  Link,
  ArrowsClockwise,
  Warning
} from '@phosphor-icons/react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Textarea } from '@/components/ui/textarea'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { 
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog'
import { ScrollArea } from '@/components/ui/scroll-area'
import { Separator } from '@/components/ui/separator'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { ConfidenceBar } from '@/components/ConfidenceBar'
import { Proposal, ProposalType } from '@/lib/types'

const proposalTypeLabels: Record<ProposalType, string> = {
  'entity-merge': 'Entity Merge',
  'entity-split': 'Entity Split',
  'alias-addition': 'Alias Addition',
  'relationship-upgrade': 'Relationship Upgrade'
}

const proposalTypeIcons: Record<ProposalType, React.ComponentType<any>> = {
  'entity-merge': GitMerge,
  'entity-split': GitBranch,
  'alias-addition': Link,
  'relationship-upgrade': ArrowsClockwise
}

export function ProposalsView() {
  const [proposals, setProposals] = useKV<Proposal[]>('proposals', [])
  const [selectedProposal, setSelectedProposal] = useState<Proposal | null>(null)
  const [reviewNotes, setReviewNotes] = useState('')
  const [activeTab, setActiveTab] = useState('pending')

  const handleApprove = (proposalId: string) => {
    setProposals(current => 
      (current || []).map(p => 
        p.id === proposalId 
          ? { ...p, status: 'approved' as const, reviewedAt: new Date().toISOString(), reviewNotes }
          : p
      )
    )
    setReviewNotes('')
  }

  const handleReject = (proposalId: string) => {
    setProposals(current => 
      (current || []).map(p => 
        p.id === proposalId 
          ? { ...p, status: 'rejected' as const, reviewedAt: new Date().toISOString(), reviewNotes }
          : p
      )
    )
    setReviewNotes('')
  }

  const filteredProposals = (proposals || []).filter(p => {
    if (activeTab === 'pending') return p.status === 'pending'
    if (activeTab === 'approved') return p.status === 'approved'
    if (activeTab === 'rejected') return p.status === 'rejected'
    return true
  })

  const getStatusIcon = (status: Proposal['status']) => {
    switch (status) {
      case 'approved':
        return <CheckCircle className="text-[oklch(0.60_0.18_145)]" size={20} weight="fill" />
      case 'rejected':
        return <XCircle className="text-destructive" size={20} weight="fill" />
      default:
        return <Clock className="text-[oklch(0.70_0.15_280)]" size={20} weight="fill" />
    }
  }

  const getStatusBadge = (status: Proposal['status']) => {
    switch (status) {
      case 'approved':
        return 'default'
      case 'rejected':
        return 'destructive'
      default:
        return 'secondary'
    }
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Reviewer Proposals</h1>
        <p className="text-muted-foreground mt-2">
          Review and approve proposals for entity merges, aliases, and relationship upgrades generated by analysis scripts.
        </p>
      </div>

      <Alert className="border-accent/30 bg-accent/10">
        <Warning className="text-accent" size={20} />
        <AlertDescription className="text-sm">
          <strong className="font-semibold">Reviewer Governance:</strong> All proposals are generated with evidence 
          and confidence scores. Approved changes are reversible and logged in the audit trail.
        </AlertDescription>
      </Alert>

      <div className="grid gap-4 md:grid-cols-4">
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium">Total Proposals</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-3xl font-bold">{(proposals || []).length}</div>
            <p className="text-xs text-muted-foreground mt-1">All proposals</p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium">Pending Review</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-3xl font-bold text-[oklch(0.70_0.15_280)]">
              {(proposals || []).filter(p => p.status === 'pending').length}
            </div>
            <p className="text-xs text-muted-foreground mt-1">Awaiting decision</p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium">Approved</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-3xl font-bold text-[oklch(0.60_0.18_145)]">
              {(proposals || []).filter(p => p.status === 'approved').length}
            </div>
            <p className="text-xs text-muted-foreground mt-1">Applied changes</p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium">Rejected</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-3xl font-bold text-destructive">
              {(proposals || []).filter(p => p.status === 'rejected').length}
            </div>
            <p className="text-xs text-muted-foreground mt-1">Declined changes</p>
          </CardContent>
        </Card>
      </div>

      <Tabs value={activeTab} onValueChange={setActiveTab}>
        <TabsList>
          <TabsTrigger value="pending">Pending</TabsTrigger>
          <TabsTrigger value="approved">Approved</TabsTrigger>
          <TabsTrigger value="rejected">Rejected</TabsTrigger>
          <TabsTrigger value="all">All</TabsTrigger>
        </TabsList>

        <TabsContent value={activeTab} className="mt-4">
          {filteredProposals.length === 0 ? (
            <Card>
              <CardContent className="flex flex-col items-center justify-center py-12">
                <Clock size={48} className="text-muted-foreground mb-4" weight="duotone" />
                <p className="text-muted-foreground text-center">
                  No proposals in this category.
                </p>
              </CardContent>
            </Card>
          ) : (
            <Card>
              <CardContent className="p-0">
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Status</TableHead>
                      <TableHead>Type</TableHead>
                      <TableHead>Confidence</TableHead>
                      <TableHead>Evidence</TableHead>
                      <TableHead>Created</TableHead>
                      <TableHead>Reversible</TableHead>
                      <TableHead className="text-right">Actions</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {filteredProposals.map((proposal) => {
                      const Icon = proposalTypeIcons[proposal.type]
                      
                      return (
                        <TableRow key={proposal.id}>
                          <TableCell>
                            <div className="flex items-center gap-2">
                              {getStatusIcon(proposal.status)}
                              <Badge variant={getStatusBadge(proposal.status)}>
                                {proposal.status}
                              </Badge>
                            </div>
                          </TableCell>
                          <TableCell>
                            <div className="flex items-center gap-2">
                              <Icon size={16} />
                              <span className="text-sm">{proposalTypeLabels[proposal.type]}</span>
                            </div>
                          </TableCell>
                          <TableCell>
                            <ConfidenceBar confidence={proposal.confidence} />
                          </TableCell>
                          <TableCell>
                            <div className="text-sm">{proposal.evidenceSnippets.length} snippets</div>
                          </TableCell>
                          <TableCell>
                            <div className="text-sm">
                              {new Date(proposal.createdAt).toLocaleDateString()}
                            </div>
                          </TableCell>
                          <TableCell>
                            {proposal.reversible ? (
                              <Badge variant="outline" className="text-xs">
                                <CheckCircle size={12} className="mr-1" />
                                Yes
                              </Badge>
                            ) : (
                              <Badge variant="secondary" className="text-xs">
                                <XCircle size={12} className="mr-1" />
                                No
                              </Badge>
                            )}
                          </TableCell>
                          <TableCell className="text-right">
                            <Dialog>
                              <DialogTrigger asChild>
                                <Button 
                                  variant="outline" 
                                  size="sm"
                                  onClick={() => setSelectedProposal(proposal)}
                                >
                                  Review
                                </Button>
                              </DialogTrigger>
                              <DialogContent className="max-w-3xl max-h-[80vh]">
                                <DialogHeader>
                                  <DialogTitle>
                                    {proposalTypeLabels[proposal.type]} Proposal
                                  </DialogTitle>
                                  <DialogDescription>
                                    Confidence: {(proposal.confidence * 100).toFixed(1)}% • 
                                    {proposal.reversible ? ' Reversible' : ' Permanent'}
                                  </DialogDescription>
                                </DialogHeader>
                                
                                <ScrollArea className="max-h-[50vh]">
                                  <div className="space-y-4">
                                    <div>
                                      <div className="text-sm font-medium mb-2">Justification</div>
                                      <p className="text-sm text-muted-foreground">{proposal.justification}</p>
                                    </div>

                                    <Separator />

                                    <div>
                                      <div className="text-sm font-medium mb-2">Proposed Change</div>
                                      <div className="bg-muted p-3 rounded font-mono text-xs">
                                        <pre className="whitespace-pre-wrap">
                                          {JSON.stringify(proposal.proposedChange, null, 2)}
                                        </pre>
                                      </div>
                                    </div>

                                    <Separator />

                                    <div>
                                      <div className="text-sm font-medium mb-2">
                                        Evidence Snippets ({proposal.evidenceSnippets.length})
                                      </div>
                                      <div className="space-y-2">
                                        {proposal.evidenceSnippets.map((snippet, idx) => (
                                          <div key={idx} className="border rounded p-3 space-y-2">
                                            <div className="text-xs text-muted-foreground">
                                              Document: {snippet.documentId}
                                              {snippet.pageNo && ` • Page ${snippet.pageNo}`}
                                            </div>
                                            <div className="text-sm bg-muted/50 p-2 rounded font-mono">
                                              {snippet.snippet}
                                            </div>
                                          </div>
                                        ))}
                                      </div>
                                    </div>

                                    {proposal.reviewNotes && (
                                      <>
                                        <Separator />
                                        <div>
                                          <div className="text-sm font-medium mb-2">Review Notes</div>
                                          <p className="text-sm text-muted-foreground">{proposal.reviewNotes}</p>
                                        </div>
                                      </>
                                    )}
                                  </div>
                                </ScrollArea>

                                {proposal.status === 'pending' && (
                                  <>
                                    <Separator />
                                    <div className="space-y-2">
                                      <label className="text-sm font-medium">Review Notes</label>
                                      <Textarea
                                        placeholder="Add notes about your decision..."
                                        value={reviewNotes}
                                        onChange={(e) => setReviewNotes(e.target.value)}
                                        rows={3}
                                      />
                                    </div>

                                    <DialogFooter>
                                      <Button 
                                        variant="destructive"
                                        onClick={() => handleReject(proposal.id)}
                                      >
                                        <XCircle size={16} weight="fill" />
                                        Reject
                                      </Button>
                                      <Button 
                                        onClick={() => handleApprove(proposal.id)}
                                      >
                                        <CheckCircle size={16} weight="fill" />
                                        Approve
                                      </Button>
                                    </DialogFooter>
                                  </>
                                )}
                              </DialogContent>
                            </Dialog>
                          </TableCell>
                        </TableRow>
                      )
                    })}
                  </TableBody>
                </Table>
              </CardContent>
            </Card>
          )}
        </TabsContent>
      </Tabs>
    </div>
  )
}
