# Copyright © 2024–2026 Faith Frontier Ecclesiastical Trust. All rights reserved.
# PROPRIETARY — See LICENSE.

# data_rights.py
"""
Data Rights and Export Compliance System
Implements the three critical compliance patterns:
1. Pointer, don't republish
2. Keep proprietary layers separate
3. Rights-aware exports
"""

import hashlib
import json
import uuid
from datetime import datetime
from enum import Enum
from pathlib import Path


class SourceType(Enum):
    """Types of data sources with different rights."""

    PUBLIC_DOMAIN = "public_domain"  # CourtListener, Justia, etc.
    CLIENT_PROVIDED = "client_provided"  # BWC footage, client documents
    OUR_ANALYSIS = "our_analysis"  # Our original work product
    PROPRIETARY_DATABASE = "proprietary_database"  # Westlaw, Lexis - NEVER export
    COPYRIGHTED_DOCUMENT = "copyrighted_document"  # Police reports, etc.
    OPRA_PUBLIC_RECORD = "opra_public_record"  # NJ public records


class DataRights:
    """Represents rights and restrictions for a piece of data."""

    def __init__(
        self,
        source_type: SourceType,
        source_name: str,
        export_allowed: bool = True,
        attribution_required: bool = True,
        attribution_text: str = "",
        fair_use_only: bool = False,
        max_excerpt_words: int = 200,
        license: str = "",
        copyright_holder: str = "",
        restriction_reason: str = "",
    ):
        self.source_type = source_type
        self.source_name = source_name
        self.export_allowed = export_allowed
        self.attribution_required = attribution_required
        self.attribution_text = attribution_text
        self.fair_use_only = fair_use_only
        self.max_excerpt_words = max_excerpt_words
        self.license = license
        self.copyright_holder = copyright_holder
        self.restriction_reason = restriction_reason


# Predefined rights profiles for common sources
RIGHTS_PROFILES = {
    "westlaw": DataRights(
        source_type=SourceType.PROPRIETARY_DATABASE,
        source_name="Westlaw",
        export_allowed=False,  # NEVER export Westlaw proprietary content
        attribution_required=False,
        restriction_reason="Proprietary database content - internal research use only",
    ),
    "lexisnexis": DataRights(
        source_type=SourceType.PROPRIETARY_DATABASE,
        source_name="LexisNexis",
        export_allowed=False,  # NEVER export Lexis proprietary content
        attribution_required=False,
        restriction_reason="Proprietary database content - internal research use only",
    ),
    "courtlistener": DataRights(
        source_type=SourceType.PUBLIC_DOMAIN,
        source_name="CourtListener",
        export_allowed=True,
        attribution_required=True,
        attribution_text="Public domain case law from CourtListener (CC0 License)",
        license="CC0 1.0 Universal (Public Domain)",
    ),
    "opra_bwc": DataRights(
        source_type=SourceType.OPRA_PUBLIC_RECORD,
        source_name="OPRA Request - Body-Worn Camera Footage",
        export_allowed=True,
        attribution_required=True,
        attribution_text="Obtained via New Jersey Open Public Records Act (OPRA)",
        license="Public record - OPRA",
    ),
    "police_report": DataRights(
        source_type=SourceType.COPYRIGHTED_DOCUMENT,
        source_name="Police Report",
        export_allowed=False,  # Full text NOT allowed
        fair_use_only=True,  # Excerpts only
        max_excerpt_words=200,
        attribution_required=True,
        restriction_reason="Copyrighted by police department - fair use excerpts only",
    ),
    "our_transcript": DataRights(
        source_type=SourceType.OUR_ANALYSIS,
        source_name="Evident Legal Tech - AI Transcript",
        export_allowed=True,
        attribution_required=True,
        attribution_text="Transcript generated by Evident Legal Tech using Whisper AI (MIT License)",
        license="Proprietary - Attorney Work Product",
        copyright_holder="[Law Firm Name]",
    ),
}


class Material:
    """Represents a material/document with rights metadata."""

    def __init__(
        self,
        filename: str,
        category: str,
        rights: DataRights,
        file_path: Path | None = None,
        acquired_by: str = "",
        acquired_date: datetime = None,
        source_url: str = "",
        content: str = "",
        is_excerpt: bool = False,
    ):
        self.filename = filename
        self.category = category
        self.rights = rights
        self.file_path = file_path
        self.acquired_by = acquired_by
        self.acquired_date = acquired_date or datetime.utcnow()
        self.source_url = source_url
        self.content = content
        self.is_excerpt = is_excerpt

        # Calculate file hash if path provided
        self.file_hash = self._calculate_hash() if file_path else None

    def _calculate_hash(self) -> str:
        """Calculate SHA-256 hash for chain of custody."""
        if not self.file_path or not self.file_path.exists():
            return ""

        sha256 = hashlib.sha256()
        with open(self.file_path, "rb") as f:
            for chunk in iter(lambda: f.read(4096), b""):
                sha256.update(chunk)
        return sha256.hexdigest()

    def validate_excerpt_length(self) -> bool:
        """Validate fair use excerpt is within limits."""
        if not self.rights.fair_use_only:
            return True

        word_count = len(self.content.split())
        return word_count <= self.rights.max_excerpt_words

    def can_export(self) -> bool:
        """Check if material can be exported."""
        if not self.rights.export_allowed:
            return False

        if self.rights.fair_use_only and not self.is_excerpt:
            return False  # Full text not allowed

        if self.is_excerpt and not self.validate_excerpt_length():
            return False  # Excerpt too long

        return True


class ExportViolation(Exception):
    """Raised when attempting to export restricted material."""

    pass


class RightsAwareExport:
    """
    Creates rights-compliant export packages with manifest.
    Implements Pattern 3: Rights-Aware Exports
    """

    def __init__(self, case_number: str, export_type: str = "discovery_production"):
        self.case_number = case_number
        self.export_type = export_type
        self.export_id = f"exp_{uuid.uuid4().hex[:12]}"
        self.materials: list[Material] = []
        self.excluded_materials: list[dict] = []

        self.manifest = {
            "export_id": self.export_id,
            "created_at": datetime.utcnow().isoformat(),
            "case_number": case_number,
            "export_type": export_type,
            "materials_included": {},
            "attribution_requirements": [],
            "excluded_materials": {"reason": "Proprietary or restricted", "items": []},
            "verification": {},
        }

    def add_material(self, material: Material) -> bool:
        """
        Add material to export if rights permit.
        Returns True if added, False if excluded.
        """
        # Validate export rights
        if not material.can_export():
            self.excluded_materials.append(
                {
                    "filename": material.filename,
                    "reason": material.rights.restriction_reason,
                    "source": material.rights.source_name,
                }
            )
            print(f"⚠️  EXCLUDED: {material.filename} - {material.rights.restriction_reason}")
            return False

        # CRITICAL: Block proprietary database content
        if material.rights.source_type == SourceType.PROPRIETARY_DATABASE:
            raise ExportViolation(
                f"BLOCKED: Cannot export proprietary database content: {material.filename}\n"
                f"Source: {material.rights.source_name}\n"
                f"Violation: Terms of service prohibit republication"
            )

        # Validate fair use excerpt length
        if material.is_excerpt and not material.validate_excerpt_length():
            raise ExportViolation(
                f"BLOCKED: Fair use excerpt exceeds maximum length: {material.filename}\n"
                f"Max allowed: {material.rights.max_excerpt_words} words\n"
                f"Actual: {len(material.content.split())} words"
            )

        # Add to materials list
        self.materials.append(material)

        # Add to manifest
        material_entry = {
            "filename": material.filename,
            "source": material.rights.source_name,
            "rights": material.rights.license or "See source attribution",
            "acquired_by": material.acquired_by,
            "acquired_date": material.acquired_date.isoformat(),
        }

        if material.file_hash:
            material_entry["sha256"] = material.file_hash

        if material.source_url:
            material_entry["source_url"] = material.source_url

        if material.is_excerpt:
            material_entry["excerpt_length"] = f"{len(material.content.split())} words"
            material_entry["fair_use_purpose"] = "Legal argument in litigation"

        # Add to appropriate category in manifest
        self.manifest["materials_included"].setdefault(material.category, []).append(material_entry)

        # Add attribution requirement
        if material.rights.attribution_required and material.rights.attribution_text:
            if material.rights.attribution_text not in self.manifest["attribution_requirements"]:
                self.manifest["attribution_requirements"].append(material.rights.attribution_text)

        print(f"✅ INCLUDED: {material.filename} - {material.rights.source_name}")
        return True

    def finalize_export(
        self, certifying_attorney: str, attorney_bar_number: str, export_directory: Path
    ) -> Path:
        """
        Finalize export package with manifest and certification.
        """
        # Add excluded materials to manifest
        if self.excluded_materials:
            self.manifest["excluded_materials"]["items"] = self.excluded_materials

        # Add third-party tool attributions (REQUIRED for open-source compliance)
        self.manifest["third_party_tools"] = [
            {
                "name": "OpenAI Whisper",
                "purpose": "Audio transcription",
                "license": "MIT License",
                "copyright": "© 2022 OpenAI",
                "url": "https://github.com/openai/whisper",
            },
            {
                "name": "pyannote.audio",
                "purpose": "Speaker diarization",
                "license": "MIT License",
                "copyright": "© 2020-2024 CNRS",
                "url": "https://github.com/pyannote/pyannote-audio",
            },
            {
                "name": "spaCy",
                "purpose": "Named entity recognition",
                "license": "MIT License",
                "copyright": "© 2016-2024 ExplosionAI GmbH",
                "url": "https://spacy.io",
            },
            {
                "name": "Hugging Face Transformers",
                "purpose": "NLP models",
                "license": "Apache License 2.0",
                "copyright": "© 2018 HuggingFace Team",
                "url": "https://huggingface.co/transformers",
            },
            {
                "name": "Flask",
                "purpose": "Web framework",
                "license": "BSD-3-Clause License",
                "copyright": "© 2010 Pallets",
                "url": "https://flask.palletsprojects.com",
            },
            {
                "name": "SQLAlchemy",
                "purpose": "Database ORM",
                "license": "MIT License",
                "copyright": "© 2005-2024 Michael Bayer",
                "url": "https://www.sqlalchemy.org",
            },
            {
                "name": "Bootstrap",
                "purpose": "CSS framework",
                "license": "MIT License",
                "copyright": "© 2011-2024 Bootstrap Authors",
                "url": "https://getbootstrap.com",
            },
            {
                "name": "FFmpeg",
                "purpose": "Audio/video processing",
                "license": "LGPL 2.1 (GPL-free build)",
                "copyright": "© 2000-2026 FFmpeg developers",
                "url": "https://ffmpeg.org",
                "build_info": "LGPL-only build from BtbN/FFmpeg-Builds (verified GPL-free)",
            },
        ]

        # Attorney certification
        self.manifest["verification"] = {
            "all_materials_permitted": len(self.excluded_materials) == 0,
            "attorney_certification": "I certify all materials comply with copyright and licensing requirements",
            "certifying_attorney": certifying_attorney,
            "attorney_bar_number": attorney_bar_number,
            "certification_date": datetime.utcnow().isoformat(),
        }

        # Create export directory
        export_path = export_directory / self.export_id
        export_path.mkdir(parents=True, exist_ok=True)

        # Write manifest
        manifest_path = export_path / "RIGHTS_MANIFEST.json"
        with open(manifest_path, "w") as f:
            json.dump(self.manifest, f, indent=2)

        # Write human-readable attribution file
        attribution_path = export_path / "ATTRIBUTION.txt"
        with open(attribution_path, "w") as f:
            f.write("EXPORT ATTRIBUTION AND RIGHTS NOTICE\n")
            f.write(f"{'=' * 60}\n\n")
            f.write(f"Export ID: {self.export_id}\n")
            f.write(f"Case Number: {self.case_number}\n")
            f.write(f"Export Date: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}\n")
            f.write(f"Certified By: {certifying_attorney} (Bar #{attorney_bar_number})\n\n")

            f.write("CONTENT ATTRIBUTION REQUIREMENTS:\n")
            f.write(f"{'-' * 60}\n")
            for attr in self.manifest["attribution_requirements"]:
                f.write(f"• {attr}\n")

            f.write("\n\nTHIRD-PARTY SOFTWARE & TOOLS:\n")
            f.write(f"{'-' * 60}\n")
            f.write("This export was generated using the following open-source tools:\n\n")
            for tool in self.manifest["third_party_tools"]:
                f.write(f"• {tool['name']} ({tool['license']})\n")
                f.write(f"  {tool['purpose']} | {tool['url']}\n")
                f.write(f"  {tool['copyright']}\n\n")

            f.write("\nFull license texts available at:\n")
            f.write("https://Evident.info/licenses\n")

            if self.excluded_materials:
                f.write("\n\nEXCLUDED MATERIALS (Not in Export):\n")
                f.write(f"{'-' * 60}\n")
                for item in self.excluded_materials:
                    f.write(f"• {item['filename']}: {item['reason']}\n")

        print(f"\n✅ Export package created: {export_path}")
        print(f"   Manifest: {manifest_path}")
        print(f"   Materials included: {len(self.materials)}")
        print(f"   Materials excluded: {len(self.excluded_materials)}")

        return export_path


# Example usage
if __name__ == "__main__":
    # Create export package
    export = RightsAwareExport(case_number="ATL-L-002794-25", export_type="discovery_production")

    # Example 1: BWC footage (ALLOWED)
    bwc = Material(
        filename="BWC_Officer_Smith_2025-01-15.mp4",
        category="bwc_videos",
        rights=RIGHTS_PROFILES["opra_bwc"],
        acquired_by="John Doe, Esq.",
        source_url="OPRA Request #2025-001",
    )
    export.add_material(bwc)

    # Example 2: Our transcript (ALLOWED)
    transcript = Material(
        filename="BWC_transcript_2025-01-15.pdf",
        category="transcripts",
        rights=RIGHTS_PROFILES["our_transcript"],
        acquired_by="Evident Legal Tech Platform",
    )
    export.add_material(transcript)

    # Example 3: Case law from CourtListener (ALLOWED)
    case_law = Material(
        filename="Garner_v_Tennessee.pdf",
        category="case_law",
        rights=RIGHTS_PROFILES["courtlistener"],
        acquired_by="Research Team",
        source_url="https://www.courtlistener.com/opinion/111150/tennessee-v-garner/",
        content="The court held that...",  # Excerpt
        is_excerpt=True,
    )
    export.add_material(case_law)

    # Example 4: Westlaw analysis (BLOCKED - will exclude)
    try:
        westlaw = Material(
            filename="KeyCite_Analysis.pdf",
            category="legal_research",
            rights=RIGHTS_PROFILES["westlaw"],
        )
        export.add_material(westlaw)  # Will be excluded, not raise
    except ExportViolation as e:
        print(f"Blocked: {e}")

    # Finalize
    export.finalize_export(
        certifying_attorney="John Doe, Esq.",
        attorney_bar_number="NJ12345",
        export_directory=Path("./exports"),
    )
