#!/usr/bin/env node
const { spawnSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const cwd = process.cwd();
const webpackConfigPath = path.join(cwd, 'webpack.config.js');
let webpackConfigContents = '';
if (fs.existsSync(webpackConfigPath)) {
  try {
    webpackConfigContents = fs.readFileSync(webpackConfigPath, 'utf8');
  } catch (e) {
    webpackConfigContents = '';
  }
}

const expectsWasm = /\.wasm|index\.wasm|wasm\b/i.test(webpackConfigContents);
if (!expectsWasm) {
  console.log('No .wasm references detected in webpack.config.js — nothing to do.');
  process.exit(0);
}

const wasmPath = path.join(cwd, 'src', 'index.wasm');
if (fs.existsSync(wasmPath)) {
  console.log('Found existing src/index.wasm — nothing to do.');
  process.exit(0);
}

// If the project provides a build:wasm script, run it.
let pkg = {};
try {
  pkg = JSON.parse(fs.readFileSync(path.join(cwd, 'package.json'), 'utf8'));
} catch (e) {
  pkg = {};
}

if (pkg.scripts && pkg.scripts['build:wasm']) {
  console.log('Running `npm run build:wasm` to generate wasm artifact...');
  const res = spawnSync('npm', ['run', 'build:wasm'], { stdio: 'inherit' });
  if (res.status !== 0) {
    console.error('`npm run build:wasm` failed.');
    process.exit(res.status || 1);
  }
  if (fs.existsSync(wasmPath)) {
    console.log('WASM artifact generated by `build:wasm`.');
    process.exit(0);
  }
  console.warn('`build:wasm` finished but did not produce src/index.wasm.');
}

// As a last resort create a small placeholder wasm module so webpack won't fail.
console.log('Creating minimal placeholder WebAssembly module at src/index.wasm');
try {
  fs.mkdirSync(path.dirname(wasmPath), { recursive: true });
  // Minimal valid wasm module header (empty module)
  const buf = Buffer.from([0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00]);
  fs.writeFileSync(wasmPath, buf);
  console.log('Placeholder wasm created.');
  process.exit(0);
} catch (err) {
  console.error('Failed to create placeholder wasm:', err);
  process.exit(1);
}
